### ISSUE TITLE
1.4.5 fails to build with Clang: `OPBufTree.c: error: initializer element is not a compile-time constant`

### ISSUE THREAD

**Issue by barracuda156** [Bioconductor/SparseArray#12]
```
  /opt/local/bin/clang-mp-16 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/S4Vectors/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/IRanges/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/XVector/include' -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk   -fopenmp -fPIC  -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64  -c OPBufTree.c -o OPBufTree.o
  OPBufTree.c:200:38: error: initializer element is not a compile-time constant
  static OPBufTree global_opbuf_tree = OPBufTree0;
                                       ^~~~~~~~~~
  1 error generated.
  make: *** [OPBufTree.o] Error 1
  ERROR: compilation failed for package ‘SparseArray’
  * removing ‘/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-SparseArray/R-SparseArray/work/build/SparseArray’
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-SparseArray/R-SparseArray/work/SparseArray" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-SparseArray/R-SparseArray/work/build --install-tests 
  Error: Failed to build R-SparseArray: command execution failed
```

Build with GCC works though.

**Comment by hpages** [comment]
This has been fixed in the latest stable version (version 1.4.8, from the `RELEASE_3_19` branch). Try to install it with:

    remotes::install_github("Bioconductor/SparseArray@RELEASE_3_19", force=TRUE)

Also please note that **SparseArray** is a Bioconductor package. Bioconductor packages should always be installed with `BiocManager::install()`. This grabs the binary which is faster to install. It also avoids any compilation issues that you may have.

**Comment by barracuda156** [comment]
Is it not there, BioConductor has 1.4.5 at the moment: https://bioconductor.org/packages/release/bioc/html/SparseArray.html

But thanks, I will just wait until 1.4.8 shows up. Installing something pre-built from external sources is not an option.

**Comment by hpages** [comment]
> Is it not there, BioConductor has 1.4.5 at the moment

It won't be there for a while. Our build system is broken and it will take some time before it's up and running again. So 1.4.8 won't show up there for a while...

**Comment by barracuda156** [comment]
Ok, got it, thanks for letting me know. Then I can grab the source from GitHub.

Closing, since this is supposed to be fixed already in the master.
