### ISSUE TITLE
How can I get Sparsearray to work in R v4.4. and BiocManager v3.19 ?

### ISSUE THREAD

**Issue by monis4567** [Bioconductor/SparseArray#8]
I am trying to  get Sparsearray to work in R v4.4. and BiocManager v3.19 but fail installing  Sparsearray .
I tried
packageurl <- "https://bioconductor.org/packages/release/bioc/src/contrib/SparseArray_1.2.4.tar.gz"
  BiocManager::install(packageurl)

But this fails with BiocManager v3.19.

**Comment by hpages** [comment]
That's not how you use `BiocManager::install()`. Please read carefully https://bioconductor.org/install/
